name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CI_PIPELINE:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: icr.io/goldeneye_images/goldeneye-ci-image:stable

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true
          # Clone all branches and history. This is needed for the upgrade tests
          fetch-depth: 0

      # Check for pre-commit updates if it is a renovate PR
      - name: Pre-commit sweeper
        run: |
          # Setup environment since GHA does not run the containers entrypoint
          . /root/.bashrc
          . /root/.profile
          ci/pre-commit-sweeper.sh

      # run pre-commit against all files
      - name: Pre-commit
        run: |
          # Setup environment since GHA does not run the containers entrypoint
          . /root/.bashrc
          . /root/.profile
          pre-commit run --all-files

      # Run tests
      - name: Run Tests
        run: go test ./... -count=1 -v -timeout 5m

      # Release
      - name: Semantic Release
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Setup environment since GHA does not run the containers entrypoint
          . /root/.bashrc
          . /root/.profile
          npx semantic-release
